# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselectioncomment',
            old_name='first_saving_date',
            new_name='date_created',
        ),
    ]
