# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0002_auto_20171209_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectioncomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userselectioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
